### ISSUE TITLE
Vmware 17 goes in bootloop after Ventura install in AMD CPU (AVX2 IS SUPPORTED!)

### ISSUE THREAD

**Issue by ToasterGithubUser** [paolo-projects/auto-unlocker#106]
![CPU-Z  16 07 2023 13_42_23](https://github.com/paolo-projects/auto-unlocker/assets/73711167/7afa5b0f-1945-4595-b812-ce0bb94e3e57)
added lines to vmx:
cpuid.0.eax = "0000:0000:0000:0000:0000:0000:0000:1011"
cpuid.0.ebx = "0111:0101:0110:1110:0110:0101:0100:0111"
cpuid.0.ecx = "0110:1100:0110:0101:0111:0100:0110:1110"
cpuid.0.edx = "0100:1001:0110:0101:0110:1110:0110:1001"
cpuid.1.eax = "0000:0000:0000:0001:0000:0110:0111:0001"
cpuid.1.ebx = "0000:0010:0000:0001:0000:1000:0000:0000"
cpuid.1.ecx = "1000:0010:1001:1000:0010:0010:0000:0011"
cpuid.1.edx = "0000:0111:1000:1011:1111:1011:1111:1111"
smc.version="0"

The https://i12bretro.github.io/tutorials/0764.html guide didn't help, anyone can help please?

**Comment by DavidDomkar** [comment]
I have the same problem, any solution to this?

**Comment by ToasterGithubUser** [comment]
[vmware.log](https://github.com/paolo-projects/auto-unlocker/files/12285552/vmware.log)
Log:

**Comment by cqgis** [comment]
I have the same problem

**Comment by doraorak** [comment]
ryzen 7 5800h same problem. using a wsl qemu/kvm works though.

**Comment by yippeekayay** [comment]
Same here, Ryzen 9 5900x, after reboot I got message Your Computer Restarted because of a Problem ..

**Comment by yippeekayay** [comment]
I solve my problem with macOS Monterey until this bug until is fixed

**Comment by rushizgithub** [comment]
> ryzen 7 5800h same problem. using a wsl qemu/kvm works though.

any guide for wsl qemu.kvm ? which version of mac works there

**Comment by doraorak** [comment]
> > ryzen 7 5800h same problem. using a wsl qemu/kvm works though.
> 
> any guide for wsl qemu.kvm ? which version of mac works there

ventura works but idk the version. Just search macos simple oneclick. The creator is notaperson535 or something.

**Comment by LaQuang** [comment]
Sonoma works with Ryzen 7 4800H. The problem is it works only with 4 cores:
 
https://www.youtube.com/watch?v=N-qa3c-V794&t=216s

**Comment by doraorak** [comment]
> Sonoma works with Ryzen 7 4800H. The problem is it works only with 4 cores:
> 
> https://www.youtube.com/watch?v=N-qa3c-V794&t=216s
thanks man finally. it seems the problem was in iso files because they dont have partitions (as far as i understood)
will try on 5800h this weekend. i will update whether or not it worked on my laptop too

**Comment by doraorak** [comment]
> Sonoma works with Ryzen 7 4800H. The problem is it works only with 4 cores:
> 
> https://www.youtube.com/watch?v=N-qa3c-V794&t=216s

unfortunately it did not work on my 5800h lenovo legion laptop. i get 
ACPI Error:[PSTA] Namespace lookup failure AE_NOT_FOUND (201609J0/psargs-463) [_STA] @0001 #002D;
No local variables are initialised for method [_STA] 
No Arguments are initialised for method [_STA]

**Comment by ToasterGithubUser** [comment]
Closed, due to i fixed my issue with opencore.
