### ISSUE TITLE
macOS 14 stuck on booting

### ISSUE THREAD

**Issue by aellul27** [paolo-projects/auto-unlocker#112]
After making some tweaks to my vmx, I am stuck on the MacOS boot icon, with no progress bar. My vmxfile, as well as my cpu info are avaliable below. I was never able to boot with the stock vmx.

BTW I am using VMware Workstation 17.0.2
[macOS 14.txt](https://github.com/paolo-projects/auto-unlocker/files/12774528/macOS.14.txt)
[cpuinfo.txt](https://github.com/paolo-projects/auto-unlocker/files/12774534/cpuinfo.txt)

EDIT: Do not use cpu flags! This causes the boot to hang.

**Comment by aellul27** [comment]
Hi everyone, finally found my issue. After removing my cpu flags (i did this because without them my boot did not hang) and playing around with my smc settings, I have found the solution. Do not run with smc.present = "TRUE", instead use smc.present = "FALSE". As well as this, do not use the cpu flags. An updated working vmx can be found below.

[macOS 14-working.txt](https://github.com/paolo-projects/auto-unlocker/files/12775863/macOS.14-working.txt)

**Comment by aellul27** [comment]
Hi everyone, finally found my issue. After removing my cpu flags (i did this because without them my boot did not hang) and playing around with my smc settings, I have found the solution. Do not run with smc.present = "TRUE", instead use smc.present = "FALSE". As well as this, do not use the cpu flags. An updated working vmx can be found below.

[macOS 14-working.txt](https://github.com/paolo-projects/auto-unlocker/files/12775863/macOS.14-working.txt)

**Comment by faiz106** [comment]
i used your file then i cannot see my allocated 160GB hard disk when using disk utitility
