### ISSUE TITLE
ERROR installing macOS Sonoma in VMware Workstation 17 Pro

### ISSUE THREAD

**Issue by orlipr84** [paolo-projects/auto-unlocker#117]
Hello friends, 

This unlocker is compatible with VMware Workstation 17 Pro version: 17.5.0 build-22583795?

I'm trying to install macOS Sonoma and when I turn on the virtual machine, after the apple banner, I get the following error: 

Your computer restarted because of a problem. Press any key or wait a few seconds to continue starting up. 

![Captura de pantalla 2024-02-17 104353](https://github.com/paolo-projects/auto-unlocker/assets/87840598/8c8153ee-0b00-43f8-bf11-e9494d6fed25)

I am using the following:
Windows 11 23H2
VMware Workstation 17 pro Version: 17.5.0 build-22583795.

My hardware it´s:
DualCore Intel Pentium Gold G6405
Gigabyte H410M S2H V2
Kingston 8 GB DDR4-2666 DDR4
Crucial 8 GB DDR4-2666 DDR4

 If anyone who reads this problem can help me, I would be infinitely grateful. Please.  🙏

**Comment by jakesvanniekerk** [comment]
Same for me I'M AFRAID :-(

_Operating System: Windows 11 Pro 64-bit
System Model: MS-7D91
Processor: Intel(R) Core(TM) i9-14900KF (32 CPUs), ~3.2GHz
Memory: 32768MB RAM
Card name: NVIDIA GeForce RTX 4060 Ti_
