### ISSUE TITLE
ERROR installing macOS Sonoma in VMware Workstation 17 Pro

### ISSUE THREAD

**Issue by orlipr84** [paolo-projects/auto-unlocker#118]
Hello friends, 

This unlocker is compatible with VMware Workstation 17 Pro version: 17.5.0 build-22583795?

I'm trying to install macOS Sonoma and when I turn on the virtual machine, after the apple banner, I get the following error: 

Your computer restarted because of a problem. Press any key or wait a few seconds to continue starting up. 

![Captura de pantalla 2024-02-17 104353](https://github.com/paolo-projects/auto-unlocker/assets/87840598/bbfa9ccd-8685-4aa2-b861-e520a0c62240)

I am using the following:
Windows 11 23H2
VMware Workstation 17 pro Version: 17.5.0 build-22583795.

My hardware it´s:
DualCore Intel Pentium Gold G6405
Gigabyte H410M S2H V2
Kingston 8 GB DDR4-2666 DDR4
Crucial 8 GB DDR4-2666 DDR4

 If anyone who reads this problem can help me, I would be infinitely grateful. Please.  🙏

**Comment by scorn242** [comment]
Hi.
Did you run the unlocker "As Administrator" before you built the VM in Workstation? 
I can confirm it works for me on that version of Workstation.

**Comment by cj89112** [comment]
I have been trying to get this to work since last night. I do run as admin, have installed and uninstalled and it's still not working.

**Comment by orlipr84** [comment]
Yes, I ran the unlocker as administrator and it installed perfectly.
I think the problem is that the microprocessor I am using does not have AVX2, one of the advanced vector instructions, which I believe is needed. I will try another PC to see if the microprocessor has this option and I will let you know. Regards.

**Comment by orlipr84** [comment]
Yes, I ran the unlocker as administrator and it installed perfectly.
I think the problem is that the microprocessor I am using does not have AVX2, one of the advanced vector instructions, which I believe is needed. I will try another PC to see if the microprocessor has this option and I will let you know. Regards.

**Comment by Mukul1127** [comment]
> Yes, I ran the unlocker as administrator and it installed perfectly. I think the problem is that the microprocessor I am using does not have AVX2, one of the advanced vector instructions, which I believe is needed. I will try another PC to see if the microprocessor has this option and I will let you know. Regards.

macOS has required AVX2 since High Sierra I believe

**Comment by Kasherpete** [comment]
I'm having this issue too I believe. VMware Workstation Pro 17, having issues installing Ventura (13). Have updated vmx file, as well as using an official Apple dmg. All recommended fixes have not had any effect - the only variable in my case is the workstation version. Does auto Unlocker support Pro 17? And if not, is there any MacOS Unlocker for it?

**Comment by LagLifeYT** [comment]
Try using the old Python based one. I switched unlockers and suddenly it works just fine. 
Works for me on VMware Workstation 17.5.1
<img width="521" alt="image" src="https://github.com/paolo-projects/auto-unlocker/assets/147282396/540db054-6322-447e-9485-409952f09e38">

**Comment by Kasherpete** [comment]
> Try using the old Python based one from like 2018. I switched unlockers and suddenly it works just fine. Works for me on VMware Workstation 17.5.1 <img alt="image" width="521" src="https://private-user-images.githubusercontent.com/147282396/308805355-540db054-6322-447e-9485-409952f09e38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxODQ2NzAsIm5iZiI6MTcwOTE4NDM3MCwicGF0aCI6Ii8xNDcyODIzOTYvMzA4ODA1MzU1LTU0MGRiMDU0LTYzMjItNDQ3ZS05NDg1LTQwOTk1MmYwOWUzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQwNTI2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MWRiM2UzZjMxZWUwNjMyZmY0ZTRkNWUxNTA5MTRmMzExYTQ4MzgxZmIyM2I5YmE2ZGE3MDYzZjQ1MDQ3MjViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r-7ZgD1pJD_2EcROSQk4gQVGCsAAeWt7UkNAiPADNjE">

Just found out it's an AMD issue, do you have an AMD chip?

**Comment by LagLifeYT** [comment]
> Just found out it's an AMD issue, do you have an AMD chip?

No, I have an Intel Core i9-13900HX.

This unlocker made the installer bootloop repeatedly. Disabling the SMC in the vmx stopped it but then macOS wouldn't boot. I think there's something related to the SMC not being properly patched.

**Comment by Mukul1127** [comment]
I heard that this project can cause bootloops, maybe try https://github.com/paolo-projects/unlocker

**Comment by adiepev** [comment]
I tried several unlockers, none of them worked....
Does anyone know an unlocker that works, to avoid the bootloop?

**Comment by Kasherpete** [comment]
To everyone in this thread, I have found the reason. Or at least I know a solution. It doesn't have anything to do with the Auto Unlocker or VMware, it's an issue with AMD x Ventura and up.

The solution is a custom OpenCore configuration. It may be a while until I have time to make a guide, but I will post the basics of how to get it all to work hopefully tonight. I got my r5 3600 to work with Ventura after at least weeks of testing 😅. Yes, iServices do work as well with a little extra configuration, as OpenCore causes the VM to ignore the VMX file.

**Comment by Kasherpete** [comment]
Oh I may have been looking at a different thread before this, as this only fixes AMD chips trying to get Ventura to work. If you have an Intel chip, it's a different problem that's most likely easier to solve.

**Comment by LagLifeYT** [comment]
> I tried several unlockers, none of them worked.... Does anyone know an unlocker that works, to avoid the bootloop?

What CPU do you have? If it's AMD, you're gonna have to either use OpenCore or not use newer macOS at all

**Comment by adiepev** [comment]
> > I tried several unlockers, none of them worked.... Does anyone know an unlocker that works, to avoid the bootloop?
> 
> What CPU do you have? If it's AMD, you're gonna have to either use OpenCore or not use newer macOS at all

I Have an Intel® Core™ i7-3770 Processor, only with AVX not AVX2! maybe that is an issue??

**Comment by orlipr84** [comment]
Hello friends,
I have resolved, the problem was that the processor I am using does not have the AVX2 instruction, required to be able to successfully install macOS Sonoma on VMware Workstation Pro 17. Thank you all for your support and collaboration.

**Comment by LagLifeYT** [comment]
> > > I tried several unlockers, none of them worked.... Does anyone know an unlocker that works, to avoid the bootloop?
> > 
> > 
> > What CPU do you have? If it's AMD, you're gonna have to either use OpenCore or not use newer macOS at all
> 
> I Have an Intel® Core™ i7-3770 Processor, only with AVX not AVX2! maybe that is an issue??

Yes, macOS 13 and higher requires AVX2, it's not going to work if you don't have that. Try Monterey, it should™ work. Although for some reason this unlocker does not work correctly, even on a i9-13900HX it won't boot. The python based on does work though, got Sonoma installed with 0 issues

**Comment by adiepev** [comment]
Thank you very much @LagLifeYT !
Monterey works fine, I had to find a workaround for 3d graphics that wouldn't work... (vmtools).

**Comment by knitesh656** [comment]
> Hello friends,
> 
> This unlocker is compatible with VMware Workstation 17 Pro version: 17.5.0 build-22583795?
> 
> I'm trying to install macOS Sonoma and when I turn on the virtual machine, after the apple banner, I get the following error:
> 
> Your computer restarted because of a problem. Press any key or wait a few seconds to continue starting up.
> 
> ![Captura de pantalla 2024-02-17 104353](https://private-user-images.githubusercontent.com/87840598/305657365-bbfa9ccd-8685-4aa2-b861-e520a0c62240.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MzU3MjIsIm5iZiI6MTcxMDYzNTQyMiwicGF0aCI6Ii84Nzg0MDU5OC8zMDU2NTczNjUtYmJmYTljY2QtODY4NS00YWEyLWI4NjEtZTUyMGEwYzYyMjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDAwMzAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NTIzZDkyMGM5NTIzOWU0NGQ2MTUxYzUxZjgxZGFlMDc2NDhkZTNlNzQzNTk4MTExMjVmMTE3NGFkOWYwYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vZByWRHo4OmfYULzi1VxxqXmHGKA1a7tK2KUfn6B9sY)
> 
> I am using the following: Windows 11 23H2 VMware Workstation 17 pro Version: 17.5.0 build-22583795.
> 
> My hardware it´s: DualCore Intel Pentium Gold G6405 Gigabyte H410M S2H V2 Kingston 8 GB DDR4-2666 DDR4 Crucial 8 GB DDR4-2666 DDR4
> 
> If anyone who reads this problem can help me, I would be infinitely grateful. Please. 🙏

**Comment by knitesh656** [comment]
@orlipr84 .

Please help to fix this out . I am facing the same issue . 
 
Please support.

**Comment by LagLifeYT** [comment]
> @orlipr84 .
> 
> Please help to fix this out . I am facing the same issue .
> 
> Please support.

If your CPU is intel, check if it supports AVX2. If it doesn't then there's simply no way to boot macOS 13 or higher.
AMD will be more of a pain since no Mac ever shipped with an AMD chip (except for graphics I guess)

**Comment by knitesh656** [comment]
Okey ! Understood. Thank  😊

**Comment by SonMaxime** [comment]
Sonoma/Ventura isnt supported actually.

**Comment by andgeno** [comment]
I just set up a working Sonoma VM on Windows 10 using VMware 17.5 Pro. I tried both, the old `unlocker` and the `auto-unlocker`. However, I compiled both myself just to be safe.

Make sure to set `CPU Processors` to `1` and `CPU Cores to `8`. MacOS is quite picky about it not only when using VMware. Also, don't enable 3D hardware acceleration.

**Comment by gerstemann** [comment]
Same issue here, but my CPU supports AVX2.

**Comment by KINGLIFER** [comment]
Please if you found a fix tell us here. Just don't say I fixed it and leave. Who does that.

**Comment by gerstemann** [comment]
I will. Tried a few things linke different unlocker or setting up a new vm. nothing is working so far.

**Comment by KINGLIFER** [comment]
> Try using the old Python based one from like 2018. I switched unlockers and suddenly it works just fine. Works for me on VMware Workstation 17.5.1 <img alt="image" width="521" src="https://private-user-images.githubusercontent.com/147282396/308805355-540db054-6322-447e-9485-409952f09e38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyODI1ODgsIm5iZiI6MTcxMjI4MjI4OCwicGF0aCI6Ii8xNDcyODIzOTYvMzA4ODA1MzU1LTU0MGRiMDU0LTYzMjItNDQ3ZS05NDg1LTQwOTk1MmYwOWUzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQwMTU4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjllMGFlNzViYjJkZmE2NGVkZTU5YTcxOWY3ZWQ2MWU3NzdkNzgyYWE0NGE5MzI3ODU0ZmViMGY1Y2IwMWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a_U7AE_3rJczdZAXkEzkXEwCEanwz32P5uRDuwBEXG0">

Link to it please?

**Comment by KINGLIFER** [comment]
> I will. Tried a few things linke different unlocker or setting up a new vm. nothing is working so far.

Sorry boss I was not talking to you. I apologize.

**Comment by LagLifeYT** [comment]
> Link to it please?

https://github.com/paolo-projects/unlocker

**Comment by LillyWho** [comment]
> > @orlipr84 .
> > Please help to fix this out . I am facing the same issue .
> > Please support.
> 
> If your CPU is intel, check if it supports AVX2. If it doesn't then there's simply no way to boot macOS 13 or higher. AMD will be more of a pain since no Mac ever shipped with an AMD chip (except for graphics I guess)

Are you quite sure about the instruction sets missing being an issue?
OpenCore Legacy Patcher actually works with Core2Duo-based machines and they don't even have AVX1.

**Comment by gputhread** [comment]
Hello It installed but after next boot the vm it went to same loop, i think unlockers need to be updated...
i5 7600
Windows 10

**Comment by avizee** [comment]
Sharing successful cases might help identify the causes.

**Comment by KINGLIFER** [comment]
> Hello friends,
> 
> This unlocker is compatible with VMware Workstation 17 Pro version: 17.5.0 build-22583795?
> 
> I'm trying to install macOS Sonoma and when I turn on the virtual machine, after the apple banner, I get the following error:
> 
> Your computer restarted because of a problem. Press any key or wait a few seconds to continue starting up.
> 
> ![Captura de pantalla 2024-02-17 104353](https://private-user-images.githubusercontent.com/87840598/305657365-bbfa9ccd-8685-4aa2-b861-e520a0c62240.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzMzOTYsIm5iZiI6MTcyODYzMzA5NiwicGF0aCI6Ii84Nzg0MDU5OC8zMDU2NTczNjUtYmJmYTljY2QtODY4NS00YWEyLWI4NjEtZTUyMGEwYzYyMjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA3NTEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlOGIyZTViY2JjZjViMDVhOThkZDc2NmI3MjE5YTdiMzBhODJiNzE2OGUxMjg0ZTMwZTNhYzI5MDlkZWViYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YWw3gYLgQoAsD1WOW4Is6fA0J5csU95ZdOexhxu8xDU)
> 
> I am using the following: Windows 11 23H2 VMware Workstation 17 pro Version: 17.5.0 build-22583795.
> 
> My hardware it´s: DualCore Intel Pentium Gold G6405 Gigabyte H410M S2H V2 Kingston 8 GB DDR4-2666 DDR4 Crucial 8 GB DDR4-2666 DDR4
> 
> If anyone who reads this problem can help me, I would be infinitely grateful. Please. 🙏

Follow this exactly.
https://docs.bluebubbles.app/server/advanced/macos-virtualization/running-a-macos-vm/deploying-macos-in-vmware-on-windows-full-guide

**Comment by AKKOU** [comment]
Does anyone fixed this problem on a AMD CPU? I'm currently using AMD R7 5800x, and I keep showing this error when I'm installing MacOS Sonoma.
I've tried reinstall the unlocker but still doesn't work at all.

**Comment by gputhread** [comment]
yes it worked, i used a different mac sonoma iso which was not beta and a patched darwin iso from somehwere i dont remember but google search will lead you, i did boot to it and build for store and its fine.

Tested on Intel i5-7600

**Comment by ZM71** [comment]
how to easily fix this without any bullshit like unlockers that does not work anyway? on windows 10 mac os 15 and up?

**Comment by DaniilGavrin** [comment]
Кто нибудь исправил проблему?
Сейчас у меня та же проблема при установке Sonoma на виртуальную машину пропатченную unlocker уже попытка наверное 15 при установке и перезагрузке уходит в ошибку с невозможностью запуска, есть ли решение?
Инструкции под AMD также добавлены были в конфигурацию

**Comment by ZM71** [comment]
Same problem with amd cpu

**Comment by ZM71** [comment]
> Кто нибудь исправил проблему?
> Сейчас у меня та же проблема при установке Sonoma на виртуальную машину пропатченную unlocker уже попытка наверное 15 при установке и перезагрузке уходит в ошибку с невозможностью запуска, есть ли решение?
> Инструкции под AMD также добавлены были в конфигурацию

Bruh answers in Russian

**Comment by ZM71** [comment]
> Кто нибудь исправил проблему?
> Сейчас у меня та же проблема при установке Sonoma на виртуальную машину пропатченную unlocker уже попытка наверное 15 при установке и перезагрузке уходит в ошибку с невозможностью запуска, есть ли решение?
> Инструкции под AMD также добавлены были в конфигурацию
There is no fix for this problem yet.

**Comment by DaniilGavrin** [comment]
Has anyone fixed the problem?
Now I have the same problem when installing Sonoma on a virtual machine patched with unlocker, probably try 15, when installing and rebooting it goes to an error with the inability to start, is there a solution?
Instructions for AMD were also added to the configuration

**Comment by ZM71** [comment]
> Has anyone fixed the problem?
> Now I have the same problem when installing Sonoma on a virtual machine patched with unlocker, probably try 15, when installing and rebooting it goes to an error with the inability to start, is there a solution?
> Instructions for AMD were also added to the configuration

Downgrade your vmware to version 17 and then run unlocker reinstall your vm and try again.

**Comment by ZM71** [comment]
> Hello friends, 
> 
> This unlocker is compatible with VMware Workstation 17 Pro version: 17.5.0 build-22583795?
> 
> I'm trying to install macOS Sonoma and when I turn on the virtual machine, after the apple banner, I get the following error: 
> 
> Your computer restarted because of a problem. Press any key or wait a few seconds to continue starting up. 
> 
> ![Captura de pantalla 2024-02-17 104353](https://github.com/paolo-projects/auto-unlocker/assets/87840598/bbfa9ccd-8685-4aa2-b861-e520a0c62240)
> 
> I am using the following:
> Windows 11 23H2
> VMware Workstation 17 pro Version: 17.5.0 build-22583795.
> 
> My hardware it´s:
> DualCore Intel Pentium Gold G6405
> Gigabyte H410M S2H V2
> Kingston 8 GB DDR4-2666 DDR4
> Crucial 8 GB DDR4-2666 DDR4
> 
>  If anyone who reads this problem can help me, I would be infinitely grateful. Please.  🙏

What about VMware workstation 17 player?

**Comment by ZM71** [comment]
> Hello friends, 
> 
> This unlocker is compatible with VMware Workstation 17 Pro version: 17.5.0 build-22583795?
> 
> I'm trying to install macOS Sonoma and when I turn on the virtual machine, after the apple banner, I get the following error: 
> 
> Your computer restarted because of a problem. Press any key or wait a few seconds to continue starting up. 
> 
> ![Captura de pantalla 2024-02-17 104353](https://github.com/paolo-projects/auto-unlocker/assets/87840598/bbfa9ccd-8685-4aa2-b861-e520a0c62240)
> 
> I am using the following:
> Windows 11 23H2
> VMware Workstation 17 pro Version: 17.5.0 build-22583795.
> 
> My hardware it´s:
> DualCore Intel Pentium Gold G6405
> Gigabyte H410M S2H V2
> Kingston 8 GB DDR4-2666 DDR4
> Crucial 8 GB DDR4-2666 DDR4
> 
>  If anyone who reads this problem can help me, I would be infinitely grateful. Please.  🙏

Downgrade to player 16 atleast that was a version that worked.

**Comment by CloudBarryChen** [comment]
hi guys. I reinstall VM and unlocker, the problem resolved!

**Comment by CloudBarryChen** [comment]
> > hi guys. I reinstall VM and unlocker, the problem resolved!
> 
> I need more information to tell you the versions of VMware, Unlocker, CPU type, and Sonoma you have installed.

please install the newest version of VMware, unlocker! My CPU is core i7. I success install macOS15 and have no infinit reboot.
vmware version: 17.5 pro, unlocker version: 427

**Comment by forkirara** [comment]
Try to set in the configuration file (.vmx):
smc.present = "FALSE"
