### ISSUE TITLE
linux "No Fusion version found in Download url location"

### ISSUE THREAD

**Issue by ja26gu** [paolo-projects/auto-unlocker#137]
It build till the very and and then gave me this error: ![image](https://github.com/user-attachments/assets/17b94be5-c1fc-4cbc-9972-f24752d7b8b1)

i tried to install it under ~
![image](https://github.com/user-attachments/assets/939f78b4-27f1-411b-8f94-8a626311a62c)

I also tried search if anyone else had the same issue but i found nobody...
I use kubuntu with vmware workstation 17.6.1
![image](https://github.com/user-attachments/assets/3173de14-bfa0-4ffd-ae2f-57a743650286)

**Comment by AstroLightz** [comment]
#135 should help you fix it.

**Comment by ja26gu** [comment]
thanks that fixed the download but mac os saddly still won't run it just bootloops like before installing the auto unblocker 
:(

**Comment by ja26gu** [comment]
ohh i'm dumb.... I just had to sign the driver again and reboot....
