### ISSUE TITLE
Does this work on Workstation Pro 16?

### ISSUE THREAD

**Issue by thepwrtank18** [paolo-projects/auto-unlocker#28]
This isn't really an issue, but more of a question.

**Comment by thepwrtank18** [comment]
After trying, it does NOT work, as VMware Tools will fail to install and the Internet doesn't work.

**Comment by thepwrtank18** [comment]
After reinstalling, both of those issues are not related to the Unlocker, but rather this:

"VMware Tools will fail to install" = the OS i'm using as a guest doesn't have SHA-2 updates installed
"and the Internet doesn't work" = VMware's fault, reason unknown

**Comment by Doomski99** [comment]
Mojave is working as intended for me.
To fix the internet, I've switched the network adapter from NAT to Bridged with the Replicate option.
