### ISSUE TITLE
Doesnt show "Apple MacOS X" menu

### ISSUE THREAD

**Issue by WindowsShadows** [paolo-projects/auto-unlocker#30]

**Comment by jmoralesv** [comment]
I think you may have to kill the VMware processes still running in the background, auto-unlocker doesn't kill them all in Windows, as per the comments in the Releases section of this repo.

I tried running auto-unlocker a second time and it worked, the Apple MacOS X option appeared in the New VM wizard.

**Comment by WindowsShadows** [comment]
Oh, but now  tried using a different unlocker, did work, but still thanks for your help
