### ISSUE TITLE
VMware Player 16 crashes on Apple logo with error "The guest operating system is not Mac OS X Server.  This virtual machine will power off."

### ISSUE THREAD

**Issue by TheSystemGuy1337** [paolo-projects/auto-unlocker#33]
So, i tried the unlocker and at the apple logo, it errors with this:

"The guest operating system is not Mac OS X Server.

This virtual machine will power off."

I tried all i can to fix it to no avail.

**Comment by dcooppan** [comment]
Hi, I also have the exact same issue - using Ubuntu 20.04 with VMWARE 16. VMWARE 15 worked fine for Mac OS 10.15. Thanks.

**Comment by qtlin** [comment]
Original python based unlocker works with 16, I am told.

**Comment by MirkoPlachta** [comment]
Yes I can confirm the python based one ist working with 16, installed it this morning and works like a charm.

**Comment by Nico04** [comment]
Can you provide a link to the python based one please ?

**Comment by qtlin** [comment]
[this one](https://github.com/mkitchingh/unlocker) is newer

**Comment by MirkoPlachta** [comment]
I'm talking about the one of Paolo you can find it here.

https://github.com/paolo-projects/unlocker

the one qtlin mentioned was last committed 201911.
Paolo last committed 202008 so thats the active one, as it seems.

**Comment by TheSystemGuy1337** [comment]
It's been four long years without any concrete fix. I am declaring this issue and project as dead. Rest in Apple Silicon, forever miss.

**Comment by thepwrtank18** [comment]
@TheSystemGuy1337 I found something! If you set `isolation.tools.osNotMacOSXServer.disable = "TRUE"` at the bottom of the VMware VMX file, you get this:
![image](https://github.com/paolo-projects/auto-unlocker/assets/57580668/62f1b08c-db9d-4c58-a21d-08f7e5fb331e)

Instead of VMware itself blocking you, it's the BIOS rom.

**Comment by TheSystemGuy1337** [comment]
> @TheSystemGuy1337 I found something! If you set `isolation.tools.osNotMacOSXServer.disable = "TRUE"` at the bottom of the VM's .VMX file, you get this: ![image](https://private-user-images.githubusercontent.com/57580668/333892689-62f1b08c-db9d-4c58-a21d-08f7e5fb331e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzkyNzIsIm5iZiI6MTcxNjczODk3MiwicGF0aCI6Ii81NzU4MDY2OC8zMzM4OTI2ODktNjJmMWIwOGMtZGI5ZC00YzU4LWEyMWQtMDhmN2U1ZmIzMzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE1NTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1OGEzZDE2NGU0NDFjZTU4MThlZDcxOGZmYWZmMzdkYTg1NzZmMjJlMmRkNDU5MDAzMTc0MzBjMDEwMGJmNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZryQ9fDHJ0N7Li-7_2DNyjNC-IOM5mTfDk67pPXuxRU)
> 
> Instead of VMware itself blocking you, it's the BIOS rom.
> 
> This doesn't exactly fix anything, but it's a step further.

**The dream of running OS X under Windows using VMware is dead. Let it rest in peace.**

The only way to "emulate" OS X is via KVM under Linux. But it's slow and has no audio support. You just revived a dead issue for no real benefit just to point out a BIOS lockout. If you are so inclined, learn assembly and patch it out. Even then, Hackintosh will be killed off when Apple fully transitions to their Mx series of processors (x being a number, example M1)

**Comment by thepwrtank18** [comment]
Modern versions of macOS work fine under VMware (albeit with limited GPU support). The error only shows on old 10.5/10.6 versions.

**Comment by TheSystemGuy1337** [comment]
> Modern versions of macOS work fine under VMware (albeit with limited GPU support). The error only shows on old 10.5/10.6 versions.

Then where can I find an ISO without having to go through a torrent only to get my internet cut by my ISP? **Nowhere.** The dream is dead, it's time that we moved on. Even then, I bet I will likely get the same error on Big Sur anyway due to the BIOS lockout, so whats the point?

**Comment by thepwrtank18** [comment]
> > Modern versions of macOS work fine under VMware (albeit with limited GPU support). The error only shows on old 10.5/10.6 versions.
> 
> Then where can I find an ISO without having to go through a torrent only to get my internet cut by my ISP? **Nowhere.** The dream is dead, it's time that we moved on. Even then, I bet I will likely get the same error on Big Sur anyway due to the BIOS lockout, so whats the point?

Archive.org, and the BIOS lockout doesn't apply on versions of macOS where there was no server version...so anything 10.7 and after.

**Comment by thepwrtank18** [comment]
https://github.com/ivanagui2/efi-unlocker/pull/1
https://github.com/thepwrtank18/efi-unlocker
![image](https://github.com/paolo-projects/auto-unlocker/assets/57580668/90f6eee9-8316-40ff-93b9-46d3bc419539)
Done.

**Comment by TheSystemGuy1337** [comment]
I will give your version a try.

**Comment by TheSystemGuy1337** [comment]
How do I get this working with VMware Player?

**Comment by thepwrtank18** [comment]
Not familiar with Player, but there should be an "x64" folder somewhere in C:\Program Files (x86)\VMware\ and it's subdirectories. From there, you'll find `EFI32.ROM`, `EFI64.ROM`, `EFI20-32.ROM`, and `EFI20-64.ROM`. Rename those to add ".bak" to the end (whatever changes the filename), put the ones made through the tool in that folder, and remove "-MACOS" from the names.

**Comment by TheSystemGuy1337** [comment]
By some uncalculated miracle, it works on OS 11. 
![image](https://github.com/paolo-projects/auto-unlocker/assets/61162037/616e604f-faea-4dae-992a-9e8a8e2c7bf1)

**Comment by TheSystemGuy1337** [comment]
I doubt the installer will get anywhere before it softlocks

**Comment by XPNGamer** [comment]
> > [@TheSystemGuy1337](https://github.com/TheSystemGuy1337) I found something! If you set `isolation.tools.osNotMacOSXServer.disable = "TRUE"` at the bottom of the VM's .VMX file, you get this: ![image](https://private-user-images.githubusercontent.com/57580668/333892689-62f1b08c-db9d-4c58-a21d-08f7e5fb331e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzkyNzIsIm5iZiI6MTcxNjczODk3MiwicGF0aCI6Ii81NzU4MDY2OC8zMzM4OTI2ODktNjJmMWIwOGMtZGI5ZC00YzU4LWEyMWQtMDhmN2U1ZmIzMzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE1NTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1OGEzZDE2NGU0NDFjZTU4MThlZDcxOGZmYWZmMzdkYTg1NzZmMjJlMmRkNDU5MDAzMTc0MzBjMDEwMGJmNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZryQ9fDHJ0N7Li-7_2DNyjNC-IOM5mTfDk67pPXuxRU)
> > Instead of VMware itself blocking you, it's the BIOS rom.
> > This doesn't exactly fix anything, but it's a step further.
> 
> **The dream of running OS X under Windows using VMware is dead. Let it rest in peace.**
> 
> The only way to "emulate" OS X is via KVM under Linux. But it's slow and has no audio support. You just revived a dead issue for no real benefit just to point out a BIOS lockout. If you are so inclined, learn assembly and patch it out. Even then, Hackintosh will be killed off when Apple fully transitions to their Mx series of processors (x being a number, example M1)

Lol, what are you talking about? You revived a dead issue 4 years later with nothing, and then get mad at someone for making some progress a month later? Powertripping at it's most. Also, the dream isn't dead, it won't be for a while. Tahoe will still be supported until 2028, and people will still be using it after.

**Comment by TheSystemGuy1337** [comment]
> Lol, what are you talking about? You revived a dead issue 4 years later with nothing, and then get mad at someone for making some progress a month later? Powertripping at it's most. Also, the dream isn't dead, it won't be for a while. Tahoe will still be supported until 2028, and people will still be using it after.

**Can we NOT stir a nearly three year old pot?** Things have changed a lot in the last 6 years and there's far easier methods of running OS X in VMware on Windows hosts, with the main one not requiring any modification at all. This whole "issue" boiled down to me being a n00b at the time and there were no better methods available to run OS X on a Windows host. And I don't know HOW I was still subscribed to this. Why doesn't GitHub autounsubcribe from old dead issues, anyway?

Either how, lets not turn GitHub into the new DramaAlert and move on. The only reason how I got notified of an issue I genuinely forgot about is due to me being subscribed the whole time.
