### ISSUE TITLE
Undefined reference error when compiling from source

### ISSUE THREAD

**Issue by Earthquake125** [paolo-projects/auto-unlocker#45]
OS: Manjaro Linux

Trying to install so I can run macOS under VMware Workstation.
The same error occurs when installing vmware-auto-unlocker-git from the AUR
I've looked around on the internet and it seems to be an error here but I'm not sure.

![Screenshot_20210416_160629](https://user-images.githubusercontent.com/59297679/115078683-f4f34500-9ecd-11eb-94d2-2f22f05603ff.png)

**Comment by daleclack** [comment]
Same error. :(

**Comment by Earthquake125** [comment]
Glad I'm not the only one, if you're on Arch I was able to install auto-unlocker through debtap with the GitHub release. The same issue occurs when trying to compile from source, though

**Comment by paolo-projects** [comment]
The makefile is outdated, but it's only a small change. You should add the libzip dependency and remove the libarchive one or compile it with cmake while I push an updated version.
