### ISSUE TITLE
issue while make in linux for vmware workstation 16

### ISSUE THREAD

**Issue by rohitghosal** [paolo-projects/auto-unlocker#47]
g++ -Wall -std=c++17 -Iinclude   -c -o src/buildsparser.o src/buildsparser.cpp
g++ -Wall -std=c++17 -Iinclude   -c -o src/unlocker.o src/unlocker.cpp
src/unlocker.cpp:28:10: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'src/unlocker.o' failed
make: *** [src/unlocker.o] Error 1
###

**Comment by pzhlkj6612** [comment]
Hi. I think you need to install "libcurl": [Search Results for curl.h - pkgs.org](https://pkgs.org/search/?q=curl.h)  
For me, I'm using "libcurl4-openssl-dev" on Ubuntu 20.10.
