### ISSUE TITLE
terminate called after throwing and instance of std::bad alloc

### ISSUE THREAD

**Issue by akarasulu** [paolo-projects/auto-unlocker#7]
**Operating System**: Mint Tricia (19.3) based on Ubuntu 18.04. 3 LTS
**Compiler Toolchain**: G++-9

```shell
root@fermi:/home/akarasulu/Downloads/auto-unlocker-1.0# ./auto-unlocker 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

The compilation went through to create the executable. I then became root and got the error above when tried to run it. Thanks in advance.

BTW thank you for the effort to replace DrDonk/unlocker: it comes just in time since the [unlocker repository](https://github.com/DrDonk/unlocker) is missing now. I guess we still have your copy though at https://github.com/paolo-projects/unlocker.

**Comment by paolo-projects** [comment]
The error is probably due to low heap memory. Are you running in a low memory or memory limited environment? what cpu and ram are you running it on?

I just tested it on ubuntu with g++9 and it works fine.

**Comment by akarasulu** [comment]
```shell
akarasulu@fermi Licenses  $ lscpu 
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               60
Model name:          Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
Stepping:            3
CPU MHz:             3310.395
CPU max MHz:         3500,0000
CPU min MHz:         800,0000
BogoMIPS:            4988.83
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            6144K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
```

I'm not even breathing heavy on this system with 32GB of RAM. Seems I have about 10G free. I can reboot and try again though and report.

**Comment by paolo-projects** [comment]
I can do very little if I can't reproduce it on my own machine. the best you can do is to debug it with gdb to see where in the code the error happens, if you're practical with it. otherwise I'd double check if the dependencies are installed correctly or maybe try with g++ 8 (add dependency **-lstdc++fs**)
