### ISSUE TITLE
Unable to select MacOS 12, only MacOS 11 is showing in the list

### ISSUE THREAD

**Issue by giorgio79** [paolo-projects/auto-unlocker#81]
Just installed the latest AutoUnlocker, but I do not see MacOS12 in the list. Any tips please?

![image](https://user-images.githubusercontent.com/283347/180114155-7af51ce7-14f3-4abf-b89c-ef4e4c5e1e56.png)

**Comment by jodkiam** [comment]
me too

**Comment by TechHopGitHub** [comment]
Just select the latest option at the time (which appears to be 11.1) I was running macOS Monterey and selecting 11 or 11.1 worked just fine.

**Comment by Forge64** [comment]
This is a VMware issue, not an unlocker one. The option is not there for anyone until VMware updates the list.

**Comment by TechHopGitHub** [comment]
I forgot to say this, but if you are running macOS 11 and higher, you MUST select 11.1, as it ended up breaking Monterey and Ventura when I selected 11.
