### ISSUE TITLE
patched but im still trial 30 days is it normal?

### ISSUE THREAD

**Issue by ravenflores** [paolo-projects/auto-unlocker#82]
![image](https://user-images.githubusercontent.com/66240114/180572966-e6513f47-e1a2-491d-a05a-ce89aec603c4.png)

**Comment by Avasam** [comment]
This isn't a crack program. It's to unlock MacOS capabilities in VMWare.

**Comment by ravenflores** [comment]
i see thanks i'll buy vmware then thank you
