### ISSUE TITLE
An error occured while applying the patch: Couldn't open file C:\Program Files (x86)\VMware\VMware Workstation\vmwarebase.dll

### ISSUE THREAD

**Issue by a-rabin** [paolo-projects/auto-unlocker#90]
Hello, 
So I attempted to install auto-unlocker and got this issue. Any fixes?

Log:
`::INFO Killing services and backing up files...
::INFO Stopping services...
::DEBUG Service "VMwareHostd" stopped successfully.
::DEBUG Service "VMAuthdService" stopped successfully.
::DEBUG Service "VMUSBArbService" stopped successfully.
::ERROR Could not kill process "vmware-tray.exe".
::INFO File "C:\Program Files (x86)\VMware\VMware Workstation\vmwarebase.dll" backup done.
::INFO File "C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx-debug.exe" backup done.
::INFO File "C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx-stats.exe" backup done.
::INFO File "C:\Program Files (x86)\VMware\VMware Workstation\x64\vmware-vmx.exe" backup done.
::INFO Patching files...
::INFO File: vmware-vmx.exe
::DEBUG Patching file: vmware-vmx.exe
::DEBUG appleSMCTableV0 (smc.version = "0")
::DEBUG appleSMCTableV0 Address      : 0x0000000000ba6e70
::DEBUG appleSMCTableV0 Private Key #: 0xF2/242
::DEBUG appleSMCTableV0 Public Key  #: 0xF0/240
::DEBUG appleSMCTableV0 Table        : 0x0000000000ba6e90
::DEBUG +LKS Key: 
::DEBUG 002 0x0000000000ba6ed8 +LKS 01 flag 0x90 0x00000001401e6420 07 
::DEBUG OSK0 Key Before:
::DEBUG 241 0x0000000000bab210 OSK0 32 ch8* 0x80 0x00000001401e6420 6f 75 72 68 61 72 64 77 6f 72 6b 62 79 74 68 65 73 65 77 6f 72 64 73 67 75 61 72 64 65 64 70 6c 
::DEBUG OSK0 Key After:
::DEBUG 241 0x0000000000bab210 OSK0 32 ch8* 0x80 0x00000001401e6420 6f 75 72 68 61 72 64 77 6f 72 6b 62 79 74 68 65 73 65 77 6f 72 64 73 67 75 61 72 64 65 64 70 6c 
::DEBUG OSK1 Key Before:
::DEBUG 242 0x0000000000bab258 OSK1 32 ch8* 0x80 0x00000001401e6420 65 61 73 65 64 6f 6e 74 73 74 65 61 6c 28 63 29 41 70 70 6c 65 43 6f 6d 70 75 74 65 72 49 6e 63 
::DEBUG OSK1 Key After:
::DEBUG 242 0x0000000000bab258 OSK1 32 ch8* 0x80 0x00000001401e6420 65 61 73 65 64 6f 6e 74 73 74 65 61 6c 28 63 29 41 70 70 6c 65 43 6f 6d 70 75 74 65 72 49 6e 63 
::DEBUG 
::DEBUG appleSMCTableV1 (smc.version = "1")
::DEBUG appleSMCTableV1 Address      : 0x0000000000bab2a0
::DEBUG appleSMCTableV1 Private Key #: 0x01B4/436
::DEBUG appleSMCTableV1 Public Key  #: 0x01B0/432
::DEBUG appleSMCTableV1 Table        : 0x0000000000bab2c0
::DEBUG +LKS Key: 
::DEBUG 004 0x0000000000bab398 +LKS 01 flag 0x90 0x00000001401e6420 01 
::DEBUG OSK0 Key Before:
::DEBUG 435 0x0000000000bb2cd0 OSK0 32 ch8* 0x90 0x00000001401e6420 6f 75 72 68 61 72 64 77 6f 72 6b 62 79 74 68 65 73 65 77 6f 72 64 73 67 75 61 72 64 65 64 70 6c 
::DEBUG OSK0 Key After:
::DEBUG 435 0x0000000000bb2cd0 OSK0 32 ch8* 0x90 0x00000001401e6420 6f 75 72 68 61 72 64 77 6f 72 6b 62 79 74 68 65 73 65 77 6f 72 64 73 67 75 61 72 64 65 64 70 6c 
::DEBUG OSK1 Key Before:
::DEBUG 436 0x0000000000bb2d18 OSK1 32 ch8* 0x90 0x00000001401e6420 65 61 73 65 64 6f 6e 74 73 74 65 61 6c 28 63 29 41 70 70 6c 65 43 6f 6d 70 75 74 65 72 49 6e 63 
::DEBUG OSK1 Key After:
::DEBUG 436 0x0000000000bb2d18 OSK1 32 ch8* 0x90 0x00000001401e6420 65 61 73 65 64 6f 6e 74 73 74 65 61 6c 28 63 29 41 70 70 6c 65 43 6f 6d 70 75 74 65 72 49 6e 63 
::DEBUG 
::INFO File: vmware-vmx-debug.exe
::DEBUG Patching file: vmware-vmx-debug.exe
::DEBUG appleSMCTableV0 (smc.version = "0")
::DEBUG appleSMCTableV0 Address      : 0x0000000000e0fda0
::DEBUG appleSMCTableV0 Private Key #: 0xF2/242
::DEBUG appleSMCTableV0 Public Key  #: 0xF0/240
::DEBUG appleSMCTableV0 Table        : 0x0000000000e0fdc0
::DEBUG +LKS Key: 
::DEBUG 002 0x0000000000e0fe08 +LKS 01 flag 0x90 0x0000000140254ee0 07 
::DEBUG OSK0 Key Before:
::DEBUG 241 0x0000000000e14140 OSK0 32 ch8* 0x80 0x0000000140254ee0 6f 75 72 68 61 72 64 77 6f 72 6b 62 79 74 68 65 73 65 77 6f 72 64 73 67 75 61 72 64 65 64 70 6c 
::DEBUG OSK0 Key After:
::DEBUG 241 0x0000000000e14140 OSK0 32 ch8* 0x80 0x0000000140254ee0 6f 75 72 68 61 72 64 77 6f 72 6b 62 79 74 68 65 73 65 77 6f 72 64 73 67 75 61 72 64 65 64 70 6c 
::DEBUG OSK1 Key Before:
::DEBUG 242 0x0000000000e14188 OSK1 32 ch8* 0x80 0x0000000140254ee0 65 61 73 65 64 6f 6e 74 73 74 65 61 6c 28 63 29 41 70 70 6c 65 43 6f 6d 70 75 74 65 72 49 6e 63 
::DEBUG OSK1 Key After:
::DEBUG 242 0x0000000000e14188 OSK1 32 ch8* 0x80 0x0000000140254ee0 65 61 73 65 64 6f 6e 74 73 74 65 61 6c 28 63 29 41 70 70 6c 65 43 6f 6d 70 75 74 65 72 49 6e 63 
::DEBUG 
::DEBUG appleSMCTableV1 (smc.version = "1")
::DEBUG appleSMCTableV1 Address      : 0x0000000000e141d0
::DEBUG appleSMCTableV1 Private Key #: 0x01B4/436
::DEBUG appleSMCTableV1 Public Key  #: 0x01B0/432
::DEBUG appleSMCTableV1 Table        : 0x0000000000e141f0
::DEBUG +LKS Key: 
::DEBUG 004 0x0000000000e142c8 +LKS 01 flag 0x90 0x0000000140254ee0 01 
::DEBUG OSK0 Key Before:
::DEBUG 435 0x0000000000e1bc00 OSK0 32 ch8* 0x90 0x0000000140254ee0 6f 75 72 68 61 72 64 77 6f 72 6b 62 79 74 68 65 73 65 77 6f 72 64 73 67 75 61 72 64 65 64 70 6c 
::DEBUG OSK0 Key After:
::DEBUG 435 0x0000000000e1bc00 OSK0 32 ch8* 0x90 0x0000000140254ee0 6f 75 72 68 61 72 64 77 6f 72 6b 62 79 74 68 65 73 65 77 6f 72 64 73 67 75 61 72 64 65 64 70 6c 
::DEBUG OSK1 Key Before:
::DEBUG 436 0x0000000000e1bc48 OSK1 32 ch8* 0x90 0x0000000140254ee0 65 61 73 65 64 6f 6e 74 73 74 65 61 6c 28 63 29 41 70 70 6c 65 43 6f 6d 70 75 74 65 72 49 6e 63 
::DEBUG OSK1 Key After:
::DEBUG 436 0x0000000000e1bc48 OSK1 32 ch8* 0x90 0x0000000140254ee0 65 61 73 65 64 6f 6e 74 73 74 65 61 6c 28 63 29 41 70 70 6c 65 43 6f 6d 70 75 74 65 72 49 6e 63 
::DEBUG 
::INFO File: vmware-vmx-stats.exe
::DEBUG Patching file: vmware-vmx-stats.exe
::DEBUG appleSMCTableV0 (smc.version = "0")
::DEBUG appleSMCTableV0 Address      : 0x0000000000bfc520
::DEBUG appleSMCTableV0 Private Key #: 0xF2/242
::DEBUG appleSMCTableV0 Public Key  #: 0xF0/240
::DEBUG appleSMCTableV0 Table        : 0x0000000000bfc540
::DEBUG +LKS Key: 
::DEBUG 002 0x0000000000bfc588 +LKS 01 flag 0x90 0x00000001401f4d30 07 
::DEBUG OSK0 Key Before:
::DEBUG 241 0x0000000000c008c0 OSK0 32 ch8* 0x80 0x00000001401f4d30 6f 75 72 68 61 72 64 77 6f 72 6b 62 79 74 68 65 73 65 77 6f 72 64 73 67 75 61 72 64 65 64 70 6c 
::DEBUG OSK0 Key After:
::DEBUG 241 0x0000000000c008c0 OSK0 32 ch8* 0x80 0x00000001401f4d30 6f 75 72 68 61 72 64 77 6f 72 6b 62 79 74 68 65 73 65 77 6f 72 64 73 67 75 61 72 64 65 64 70 6c 
::DEBUG OSK1 Key Before:
::DEBUG 242 0x0000000000c00908 OSK1 32 ch8* 0x80 0x00000001401f4d30 65 61 73 65 64 6f 6e 74 73 74 65 61 6c 28 63 29 41 70 70 6c 65 43 6f 6d 70 75 74 65 72 49 6e 63 
::DEBUG OSK1 Key After:
::DEBUG 242 0x0000000000c00908 OSK1 32 ch8* 0x80 0x00000001401f4d30 65 61 73 65 64 6f 6e 74 73 74 65 61 6c 28 63 29 41 70 70 6c 65 43 6f 6d 70 75 74 65 72 49 6e 63 
::DEBUG 
::DEBUG appleSMCTableV1 (smc.version = "1")
::DEBUG appleSMCTableV1 Address      : 0x0000000000c00950
::DEBUG appleSMCTableV1 Private Key #: 0x01B4/436
::DEBUG appleSMCTableV1 Public Key  #: 0x01B0/432
::DEBUG appleSMCTableV1 Table        : 0x0000000000c00970
::DEBUG +LKS Key: 
::DEBUG 004 0x0000000000c00a48 +LKS 01 flag 0x90 0x00000001401f4d30 01 
::DEBUG OSK0 Key Before:
::DEBUG 435 0x0000000000c08380 OSK0 32 ch8* 0x90 0x00000001401f4d30 6f 75 72 68 61 72 64 77 6f 72 6b 62 79 74 68 65 73 65 77 6f 72 64 73 67 75 61 72 64 65 64 70 6c 
::DEBUG OSK0 Key After:
::DEBUG 435 0x0000000000c08380 OSK0 32 ch8* 0x90 0x00000001401f4d30 6f 75 72 68 61 72 64 77 6f 72 6b 62 79 74 68 65 73 65 77 6f 72 64 73 67 75 61 72 64 65 64 70 6c 
::DEBUG OSK1 Key Before:
::DEBUG 436 0x0000000000c083c8 OSK1 32 ch8* 0x90 0x00000001401f4d30 65 61 73 65 64 6f 6e 74 73 74 65 61 6c 28 63 29 41 70 70 6c 65 43 6f 6d 70 75 74 65 72 49 6e 63 
::DEBUG OSK1 Key After:
::DEBUG 436 0x0000000000c083c8 OSK1 32 ch8* 0x90 0x00000001401f4d30 65 61 73 65 64 6f 6e 74 73 74 65 61 6c 28 63 29 41 70 70 6c 65 43 6f 6d 70 75 74 65 72 49 6e 63 
::DEBUG 
::INFO File: vmwarebase.dll
::DEBUG GOS Patching: vmwarebase.dll
::ERROR Couldn't open file C:\Program Files (x86)\VMware\VMware Workstation\vmwarebase.dll
`

**Comment by tgreve15** [comment]
I got that twice last night as well. Rebooted my machine and tried again
and it worked. Suspect if you've run vmware workstation since restarting
this dll is still open for some reason.

**Comment by dynomete** [comment]
I am having the same problem too, even after restarting my pc, still got the same error. I actually found the only way I could get it working for me at least was putting the Unlocker.exe directly in the install path which got it to work. If @tgreve15's method doesn't work I recommend you trying this aswell, although it may have only worked because I have my VMWare installed in a different directory instead of the default one.

**Comment by a-rabin** [comment]
Thanks for the help. I managed to get it to work my running the Unlocker in the desktop.
