### ISSUE TITLE
Bootloop after install

### ISSUE THREAD

**Issue by zachariapopcorn** [paolo-projects/auto-unlocker#96]
I'm able to install MacOS Ventura just fine, but when it's done, it boot loops over and over again, and none of the solutions that I've found worked. I followed the following guide when it comes to the vmx file: https://i12bretro.github.io/tutorials/0764.html

Anyone know what I need to do now to fix this issue?

**Comment by mikeyo** [comment]
Same, let me know if you ever resolve this. My CPU is 3950x and I am told that Ventura doesnt work with this processor without patches.

**Comment by zachariapopcorn** [comment]
> Same, let me know if you ever resolve this. My CPU is 3950x and I am told that Ventura doesnt work with this processor without patches.

So I did research and I found it wasn't possible for VMware to run MacOS Ventura, so I settled for the version below it, which worked flawlessly. If it is possible, I couldnt find how to do it
